name: Waka Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-stats:
    name: Update Coding Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: "coding-stats"
          
          SHOW_TITLE: false
          TIME_RANGE: "all_time"
          LANG_COUNT: 5
          BLOCKS: "░▒▓█"
          SHOW_TIME: true
          SHOW_TOTAL: true
          IGNORED_LANGUAGES: "YAML JSON Markdown Text" 

          COMMIT_MESSAGE: "docs: update coding metrics [skip ci]"
          TARGET_BRANCH: "main"

          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_LOC_CHART: false
          API_BASE_URL: "https://waka-stats.aes.my.id:2087/api"
